name: OpenMinetopia
version: '1.0-SNAPSHOT'
main: nl.openminetopia.OpenMinetopia
loader: nl.openminetopia.OpenMinetopiaLoader
api-version: '1.21'
authors: [ 'KaasPlakje', 'OmeJan', 'TheBathDuck', 'Jazzkuh' ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: AFTER
      required: true