name: OpenMinetopia
version: '${project.version}'
main: nl.openminetopia.OpenMinetopia
loader: nl.openminetopia.OpenMinetopiaLoader
api-version: '1.20'
dependencies:
  server:
    WorldGuard:
      load: AFTER
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: true